export default {
    title: "Eile Pomex",
    description: {
        tr: "Eile Pomex Yapı Kimyasalları, yenilikçi, sürdürülebilir, yüksek performanslı inşaat malzemeleri üretir. Depreme, yangına dayanıklı, ısı-ses yalıtımlı çözümler sunar.",
        en: "Eile Pomex Construction Chemicals produces innovative, sustainable, and high-performance building materials. It offers durable, fire-resistant, and thermal-acoustic insulation solutions.",
    },
    headerTitle: "Eile Pomex",
    theme: "system",
    siteUrl: "https://www.eilepomex.com/",
    siteLogo: "https://www.eilepomex.com/assets/logos/eile.png",
    socialBanner: "https://www.eilepomex.com/assets/logos/eilepomex-round.png",
    email: "info@eilepomex.com",
    linkedin: "https://www.linkedin.com/company/eilepomex",
    instagram: "https://www.instagram.com/eilepomex",
    facebokk: "https://www.facebook.com/eilepomex",
    keywords: {
        tr: [
            "Yapı Kimyasalları",
            "yapı kimyasallarında lider üretici",
            "çevre dostu yapı malzemeleri",
            "sürdürülebilir yapı malzemeleri",
            "enerji verimli izolasyon ürünleri",
            "yüksek performanslı yapı kimyasalları",
            "inovatif yapı ürünleri",
            "su yalıtımı için en iyi malzemeler",
            "ısı yalıtımı nasıl yapılır",
            "bina güçlendirme ürünleri nelerdir",
            "ses yalıtımı fiyatları 2025",
            "eile pomex",
            "eile",
            "pomex",
            "pomeks",
        ],
        en: [
            "Construction Chemicals",
            "leading manufacturer of construction chemicals",
            "environmentally friendly building materials",
            "sustainable building materials",
            "energy efficient insulation products",
            "high performance construction chemicals",
            "innovative building products",
            "best materials for waterproofing",
            "How to make thermal insulation",
            "What are building reinforcement products",
            "sound insulation prices 2025",
            "eile pomex",
            "eile",
            "pomex",
            "pomeks",
        ],
    },
    productsPage: {
        title: {
            tr: "Ürünler",
            en: "Products",
        },
        description: { tr: "Eile Pomex Ürünler", en: "Eile Pomex Products" },
        keywords: { tr: [], en: [] },
    },
    aboutPage: {
        title: {
            tr: "Hakkımızda",
            en: "About Us",
        },
        description: { tr: "Eile Pomex Hakkımızda", en: "Eile Pomex About Us" },
        keywords: { tr: [], en: [] },
    },
    contactPage: {
        title: {
            tr: "İletişim",
            en: "Contact",
        },
        description: { tr: "Eile Pomex İletişim", en: "Eile Pomex Contact" },
        keywords: { tr: [], en: [] },
    },
    docsPage: {
        title: {
            tr: "Sertifikalar",
            en: "Certificates",
        },
        description: {
            tr: "Eile Pomex Sertifikalar",
            en: "Eile Pomex Certificates",
        },
        keywords: { tr: [], en: [] },
    },
};
