import productData from "@/data/products.json";
import { routing } from "@/i18n/routing";
import { getMessages, setRequestLocale } from "next-intl/server";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export function generateStaticParams() {
    let list = [];
    productData.map((item) => {
        list.push({
            productKey: item.key.toString(),
        });
        if (item.subGroups) {
            list.push({
                productKey: item.key.toString() + "-0",
            });
            item.subGroups.forEach((el) => {
                list.push({
                    productKey: el.key.toString(),
                });
            });
        }
    });
    list.unshift({ productKey: "0" });
    return list;
}

export default async function ProductsLayout({ children, params }) {
    const { locale } = await params;
    if (!routing.locales.includes(locale)) {
        notFound();
    }
    setRequestLocale(locale);
    return (
        <div
            style={{
                width: "100%",
                height: "100%",
                overflow: "auto",
            }}
        >
            {children}
        </div>
    );
}
