import "./globals.css";
import { routing } from "@/i18n/routing";
import { NextIntlClientProvider } from "next-intl";
import { getMessages, setRequestLocale } from "next-intl/server";
import Header from "@/components/header";
import Footer from "@/components/footer";
import { Play } from "next/font/google";
import Head from "next/head";

const play = Play({
    weight: "400",
    subsets: ["latin"],
});

export const metadata = {
    title: "Eile Pomex",
    description: "Generated by create next app",
};

export function generateStaticParams() {
    return routing.locales.map((locale) => ({ locale }));
}

export default async function LocaleLayout({ children, params }) {
    const { locale } = await params;
    if (!routing.locales.includes(locale)) {
        notFound();
    }
    const messages = await getMessages();
    setRequestLocale(locale);
    return (
        <html lang={locale}>
            <body className={play.className}>
                <NextIntlClientProvider messages={messages}>
                    <div
                        style={{
                            width: "100%",
                            height: "100%",
                            overflow: "auto",
                        }}
                    >
                        <Header />
                        {children}
                        <Footer />
                    </div>
                </NextIntlClientProvider>
            </body>
        </html>
    );
}
