import productList from "@/data/productList.json";
import { routing } from "@/i18n/routing";
import { setRequestLocale } from "next-intl/server";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export function generateStaticParams() {
    return productList.map((item) => {
        return { productId: item.id.toString() };
    });
}

export default async function ProductDetailsLayout({ children, params }) {
    const { locale } = await params;
    if (!routing.locales.includes(locale)) {
        notFound();
    }
    setRequestLocale(locale);
    return (
        <div
            style={{
                width: "100%",
                height: "100%",
                overflow: "auto",
                paddingTop: "30px",
            }}
        >
            {children}
        </div>
    );
}
